version: '3.7'
services:
  web:
    build: .
    image: nuxt-app:1.0.0
    ports:
      - '34099:8000'
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=gustaw.daniel@gmail.com
      - VIRTUAL_PORT=34099
